sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ya1rd0cker/docker-and-kubernetes/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true ya1rd0cker/docker-and-kubernetes/frontend npm run test
